if(DEFINED test_bhvutil_fixedturn_TESTS)
  foreach(_moos_test IN LISTS test_bhvutil_fixedturn_TESTS)
    set(_moos_labels [=[bhvutil;BHV_FixedTurn]=])
    if(_moos_test MATCHES [=[\.FixedTurnTest\.]=])
      list(APPEND _moos_labels [=[FixedTurn]=])
    endif()
    if(_moos_test MATCHES [=[\.FixedTurnSetTest\.]=])
      list(APPEND _moos_labels [=[FixedTurnSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
