if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/logutils/AppLog/test_logutils_app_log[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/logutils/AppLog/test_logutils_app_log[1]_tests.cmake")
else()
  add_test(test_logutils_app_log_NOT_BUILT test_logutils_app_log_NOT_BUILT)
endif()
