if(DEFINED test_logutils_app_log_TESTS)
  foreach(_moos_test IN LISTS test_logutils_app_log_TESTS)
    set(_moos_labels [=[logutils]=])
    if(_moos_test MATCHES [=[\.AppLogEntryTest\.]=])
      list(APPEND _moos_labels [=[AppLogEntry]=])
    endif()
    if(_moos_test MATCHES [=[\.AppLogPlotTest\.]=])
      list(APPEND _moos_labels [=[AppLogPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorAppLogPlotTest\.]=])
      list(APPEND _moos_labels [=[Populator_AppLogPlot]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
