if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogmhash/MHashReporter/test_alogmhash_mhash_reporter[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogmhash/MHashReporter/test_alogmhash_mhash_reporter[1]_tests.cmake")
else()
  add_test(test_alogmhash_mhash_reporter_NOT_BUILT test_alogmhash_mhash_reporter_NOT_BUILT)
endif()
