if(DEFINED test_mbutil_vardatapair_TESTS)
  foreach(_moos_test IN LISTS test_mbutil_vardatapair_TESTS)
    set(_moos_labels [=[mbutil]=])
    if(_moos_test MATCHES [=[\.VarDataPairTest\.]=])
      list(APPEND _moos_labels [=[VarDataPair]=])
    endif()
    if(_moos_test MATCHES [=[\.VarDataPairUtilsTest\.]=])
      list(APPEND _moos_labels [=[VarDataPairUtils]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
