if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/mbutil/VarDataPair/test_mbutil_vardatapair[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/mbutil/VarDataPair/test_mbutil_vardatapair[1]_tests.cmake")
else()
  add_test(test_mbutil_vardatapair_NOT_BUILT test_mbutil_vardatapair_NOT_BUILT)
endif()
