if(DEFINED test_logutils_core_alog_TESTS)
  foreach(_moos_test IN LISTS test_logutils_core_alog_TESTS)
    set(_moos_labels [=[logutils;LogUtils;ALogParsing]=])
    if(_moos_test MATCHES [=[\.ALogEntryTest\.]=])
      list(APPEND _moos_labels [=[ALogEntry]=])
    endif()
    if(_moos_test MATCHES [=[\.LogUtilsFieldParsingTest\.]=])
      list(APPEND _moos_labels [=[LogUtils]=])
      list(APPEND _moos_labels [=[ALogParsing]=])
    endif()
    if(_moos_test MATCHES [=[\.LogUtilsTimeTest\.]=])
      list(APPEND _moos_labels [=[LogUtils]=])
      list(APPEND _moos_labels [=[ALogParsing]=])
    endif()
    if(_moos_test MATCHES [=[\.LogUtilsIndexTest\.]=])
      list(APPEND _moos_labels [=[LogUtils]=])
      list(APPEND _moos_labels [=[ALogParsing]=])
    endif()
    if(_moos_test MATCHES [=[\.LogUtilsVectorKeyTest\.]=])
      list(APPEND _moos_labels [=[LogUtils]=])
      list(APPEND _moos_labels [=[ALogParsing]=])
    endif()
    if(_moos_test MATCHES [=[\.LogUtilsFileParsingTest\.]=])
      list(APPEND _moos_labels [=[LogUtils]=])
      list(APPEND _moos_labels [=[ALogParsing]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
