if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogtm/TGrepHandler/test_alogtm_tgrep_handler[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogtm/TGrepHandler/test_alogtm_tgrep_handler[1]_tests.cmake")
else()
  add_test(test_alogtm_tgrep_handler_NOT_BUILT test_alogtm_tgrep_handler_NOT_BUILT)
endif()
