if(DEFINED test_pechovar_echo_var_TESTS)
  foreach(_moos_test IN LISTS test_pechovar_echo_var_TESTS)
    set(_moos_labels [=[pechovar;EchoVar]=])
    if(_moos_test MATCHES [=[\.EchoVarMappingTest\.]=])
      list(APPEND _moos_labels [=[EchoVar]=])
    endif()
    if(_moos_test MATCHES [=[\.EchoVarFlipEntryTest\.]=])
      list(APPEND _moos_labels [=[EchoVar]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
