if(DEFINED test_uplotviewer_partition_record_TESTS)
  foreach(_moos_test IN LISTS test_uplotviewer_partition_record_TESTS)
    set(_moos_labels [=[uplotviewer;PartitionRecord]=])
    if(_moos_test MATCHES [=[\.PartitionRecordTest\.]=])
      list(APPEND _moos_labels [=[PartitionRecord]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
