if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ucommand/CommandFolio/test_ucommand_command_folio[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ucommand/CommandFolio/test_ucommand_command_folio[1]_tests.cmake")
else()
  add_test(test_ucommand_command_folio_NOT_BUILT test_ucommand_command_folio_NOT_BUILT)
endif()
