if(DEFINED test_ucommand_command_folio_TESTS)
  foreach(_moos_test IN LISTS test_ucommand_command_folio_TESTS)
    set(_moos_labels [=[ucommand]=])
    if(_moos_test MATCHES [=[\.CommandItemTest\.]=])
      list(APPEND _moos_labels [=[CommandItem]=])
    endif()
    if(_moos_test MATCHES [=[\.CommandFolioTest\.]=])
      list(APPEND _moos_labels [=[CommandFolio]=])
    endif()
    if(_moos_test MATCHES [=[\.CommandPostTest\.]=])
      list(APPEND _moos_labels [=[CommandPost]=])
    endif()
    if(_moos_test MATCHES [=[\.CommandSummaryTest\.]=])
      list(APPEND _moos_labels [=[CommandSummary]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
