if(DEFINED test_realm_core_TESTS)
  foreach(_moos_test IN LISTS test_realm_core_TESTS)
    set(_moos_labels [=[realm;pMarineViewer;REALMCAST;REALMCAST_CHANNELS;WATCHCAST]=])
    if(_moos_test MATCHES [=[\.RealmCastTest\.]=])
      list(APPEND _moos_labels [=[RealmCast]=])
    endif()
    if(_moos_test MATCHES [=[\.RealmSummaryTest\.]=])
      list(APPEND _moos_labels [=[RealmSummary]=])
    endif()
    if(_moos_test MATCHES [=[\.WatchCastTest\.]=])
      list(APPEND _moos_labels [=[WatchCast]=])
    endif()
    if(_moos_test MATCHES [=[\.RealmCastSetTest\.]=])
      list(APPEND _moos_labels [=[RealmCastSet]=])
    endif()
    if(_moos_test MATCHES [=[\.RealmCastTreeTest\.]=])
      list(APPEND _moos_labels [=[RealmCastTree]=])
    endif()
    if(_moos_test MATCHES [=[\.RealmRepoTest\.]=])
      list(APPEND _moos_labels [=[RealmRepo]=])
      list(APPEND _moos_labels [=[WatchCluster]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
