if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/ArcUtils/test_geometry_arcutils[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/ArcUtils/test_geometry_arcutils[1]_tests.cmake")
else()
  add_test(test_geometry_arcutils_NOT_BUILT test_geometry_arcutils_NOT_BUILT)
endif()
