if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ivpsolve/ProblemSolving/test_ivpsolve_problem_solving[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ivpsolve/ProblemSolving/test_ivpsolve_problem_solving[1]_tests.cmake")
else()
  add_test(test_ivpsolve_problem_solving_NOT_BUILT test_ivpsolve_problem_solving_NOT_BUILT)
endif()
