if(DEFINED test_ivpsolve_problem_solving_TESTS)
  foreach(_moos_test IN LISTS test_ivpsolve_problem_solving_TESTS)
    set(_moos_labels [=[ivpsolve;pHelmIvP;math]=])
    if(_moos_test MATCHES [=[\.ProblemTest\.]=])
      list(APPEND _moos_labels [=[Problem]=])
    endif()
    if(_moos_test MATCHES [=[\.IvPProblemTest\.]=])
      list(APPEND _moos_labels [=[IvPProblem]=])
    endif()
    if(_moos_test MATCHES [=[\.IvPProblemVariantTest\.]=])
      list(APPEND _moos_labels [=[IvPProblem_v2]=])
      list(APPEND _moos_labels [=[IvPProblem_v3]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorIPPTest\.]=])
      list(APPEND _moos_labels [=[PopulatorIPP]=])
      list(APPEND _moos_labels [=[FunctionEncoder]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
