if(DEFINED test_mbutil_color_TESTS)
  foreach(_moos_test IN LISTS test_mbutil_color_TESTS)
    set(_moos_labels [=[mbutil]=])
    if(_moos_test MATCHES [=[\.ColorPackTest\.]=])
      list(APPEND _moos_labels [=[ColorPack]=])
    endif()
    if(_moos_test MATCHES [=[\.ColorParseTest\.]=])
      list(APPEND _moos_labels [=[ColorParse]=])
    endif()
    if(_moos_test MATCHES [=[\.TermColorTest\.]=])
      list(APPEND _moos_labels [=[TermColor]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
