if(DEFINED test_polar_plot_TESTS)
  foreach(_moos_test IN LISTS test_polar_plot_TESTS)
    set(_moos_labels [=[polar;uSimMarineV22;uSimMarineV23]=])
    if(_moos_test MATCHES [=[\.PolarPlotTest\.]=])
      list(APPEND _moos_labels [=[PolarPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.WindModelTest\.]=])
      list(APPEND _moos_labels [=[WindModel]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorPolarPlotTest\.]=])
      list(APPEND _moos_labels [=[PopulatorPolarPlot]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
