if(DEFINED test_geometry_xyformatutils_vector_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_vector_TESTS)
    set(_moos_labels [=[geometry;formats;math]=])
    if(_moos_test MATCHES [=[\.XYVectorTest\.]=])
      list(APPEND _moos_labels [=[XYVector]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsVectorTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsVector]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
