if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/mbutil/MacroAndHash/test_mbutil_macro_hash[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/mbutil/MacroAndHash/test_mbutil_macro_hash[1]_tests.cmake")
else()
  add_test(test_mbutil_macro_hash_NOT_BUILT test_mbutil_macro_hash_NOT_BUILT)
endif()
