if(DEFINED test_mbutil_macro_hash_TESTS)
  foreach(_moos_test IN LISTS test_mbutil_macro_hash_TESTS)
    set(_moos_labels [=[mbutil]=])
    if(_moos_test MATCHES [=[\.MacroUtilsTest\.]=])
      list(APPEND _moos_labels [=[MacroUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.HashUtilsTest\.]=])
      list(APPEND _moos_labels [=[HashUtils]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
