if(DEFINED test_geometry_xyformatutils_point_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_point_TESTS)
    set(_moos_labels [=[geometry;formats]=])
    if(_moos_test MATCHES [=[\.XYPointTest\.]=])
      list(APPEND _moos_labels [=[XYPoint]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsPointTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsPoint]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
