if(DEFINED test_contacts_noderecord_TESTS)
  foreach(_moos_test IN LISTS test_contacts_noderecord_TESTS)
    set(_moos_labels [=[contacts;NodeReport]=])
    if(_moos_test MATCHES [=[\.NodeRecordTest\.]=])
      list(APPEND _moos_labels [=[NodeRecord]=])
    endif()
    if(_moos_test MATCHES [=[\.NodeRecordUtilsTest\.]=])
      list(APPEND _moos_labels [=[NodeRecordUtils]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
