if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/contacts/NodeRecord/test_contacts_noderecord[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/contacts/NodeRecord/test_contacts_noderecord[1]_tests.cmake")
else()
  add_test(test_contacts_noderecord_NOT_BUILT test_contacts_noderecord_NOT_BUILT)
endif()
