if(DEFINED test_geometry_field_artifacts_TESTS)
  foreach(_moos_test IN LISTS test_geometry_field_artifacts_TESTS)
    set(_moos_labels [=[geometry;FieldArtifacts;current;artifacts]=])
    if(_moos_test MATCHES [=[\.ArtifactUtilsLawnmowerTest\.]=])
      list(APPEND _moos_labels [=[ArtifactUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.ArtifactUtilsArtifactsTest\.]=])
      list(APPEND _moos_labels [=[ArtifactUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.CurrentFieldTest\.]=])
      list(APPEND _moos_labels [=[CurrentField]=])
    endif()
    if(_moos_test MATCHES [=[\.OpFieldTest\.]=])
      list(APPEND _moos_labels [=[OpField]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
