if(DEFINED test_geometry_xygrid_family_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xygrid_family_TESTS)
    set(_moos_labels [=[geometry;grid;formats]=])
    if(_moos_test MATCHES [=[\.XYGridTest\.]=])
      list(APPEND _moos_labels [=[XYGrid]=])
    endif()
    if(_moos_test MATCHES [=[\.XYHexGridTest\.]=])
      list(APPEND _moos_labels [=[XYHexGrid]=])
    endif()
    if(_moos_test MATCHES [=[\.XYHexagonTest\.]=])
      list(APPEND _moos_labels [=[XYHexagon]=])
    endif()
    if(_moos_test MATCHES [=[\.XYGridUpdateTest\.]=])
      list(APPEND _moos_labels [=[XYGridUpdate]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
