if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYGridFamily/test_geometry_xygrid_family[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYGridFamily/test_geometry_xygrid_family[1]_tests.cmake")
else()
  add_test(test_geometry_xygrid_family_NOT_BUILT test_geometry_xygrid_family_NOT_BUILT)
endif()
