if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/manifest/Populator/test_manifest_populator[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/manifest/Populator/test_manifest_populator[1]_tests.cmake")
else()
  add_test(test_manifest_populator_NOT_BUILT test_manifest_populator_NOT_BUILT)
endif()
