if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/bhvutil/AOFs/test_bhvutil_aofs[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/bhvutil/AOFs/test_bhvutil_aofs[1]_tests.cmake")
else()
  add_test(test_bhvutil_aofs_NOT_BUILT test_bhvutil_aofs_NOT_BUILT)
endif()
