if(DEFINED test_bhvutil_aofs_TESTS)
  foreach(_moos_test IN LISTS test_bhvutil_aofs_TESTS)
    set(_moos_labels [=[bhvutil;AOF]=])
    if(_moos_test MATCHES [=[\.AOFWaypointTest\.]=])
      list(APPEND _moos_labels [=[AOF_Waypoint]=])
      list(APPEND _moos_labels [=[BHV_Waypoint]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFContactTest\.]=])
      list(APPEND _moos_labels [=[AOF_Contact]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFAvoidCollisionTest\.]=])
      list(APPEND _moos_labels [=[AOF_AvoidCollision]=])
      list(APPEND _moos_labels [=[BHV_AvoidCollision]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFAvoidCollisionDepthTest\.]=])
      list(APPEND _moos_labels [=[AOF_AvoidCollisionDepth]=])
      list(APPEND _moos_labels [=[BHV_AvoidCollisionDepth]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFAvoidObstacleV24Test\.]=])
      list(APPEND _moos_labels [=[AOF_AvoidObstacleV24]=])
      list(APPEND _moos_labels [=[BHV_AvoidObstacleV24]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFAvoidWallsTest\.]=])
      list(APPEND _moos_labels [=[AOF_AvoidWalls]=])
      list(APPEND _moos_labels [=[BHV_AvoidWalls]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFCutRangeCPATest\.]=])
      list(APPEND _moos_labels [=[AOF_CutRangeCPA]=])
      list(APPEND _moos_labels [=[BHV_CutRange]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFAttractorCPATest\.]=])
      list(APPEND _moos_labels [=[AOF_AttractorCPA]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFShadowTest\.]=])
      list(APPEND _moos_labels [=[AOF_Shadow]=])
      list(APPEND _moos_labels [=[BHV_Shadow]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
