if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYArc/test_geometry_xyarc[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYArc/test_geometry_xyarc[1]_tests.cmake")
else()
  add_test(test_geometry_xyarc_NOT_BUILT test_geometry_xyarc_NOT_BUILT)
endif()
