if(DEFINED test_ufield_hostrecord_TESTS)
  foreach(_moos_test IN LISTS test_ufield_hostrecord_TESTS)
    set(_moos_labels [=[ufield;PHI_HOST_INFO;NODE_BROKER]=])
    if(_moos_test MATCHES [=[\.HostRecordTest\.]=])
      list(APPEND _moos_labels [=[HostRecord]=])
    endif()
    if(_moos_test MATCHES [=[\.HostRecordUtilsTest\.]=])
      list(APPEND _moos_labels [=[HostRecordUtils]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
