if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/logutils/AnalysisPlots/test_logutils_analysis_plots[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/logutils/AnalysisPlots/test_logutils_analysis_plots[1]_tests.cmake")
else()
  add_test(test_logutils_analysis_plots_NOT_BUILT test_logutils_analysis_plots_NOT_BUILT)
endif()
