if(DEFINED test_logutils_analysis_plots_TESTS)
  foreach(_moos_test IN LISTS test_logutils_analysis_plots_TESTS)
    set(_moos_labels [=[logutils]=])
    if(_moos_test MATCHES [=[\.TaskDiaryTest\.]=])
      list(APPEND _moos_labels [=[TaskDiary]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorTaskDiaryTest\.]=])
      list(APPEND _moos_labels [=[Populator_TaskDiary]=])
    endif()
    if(_moos_test MATCHES [=[\.HelmPlotTest\.]=])
      list(APPEND _moos_labels [=[HelmPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorHelmPlotsTest\.]=])
      list(APPEND _moos_labels [=[Populator_HelmPlots]=])
    endif()
    if(_moos_test MATCHES [=[\.IPFPlotTest\.]=])
      list(APPEND _moos_labels [=[IPF_Plot]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorIPFPlotTest\.]=])
      list(APPEND _moos_labels [=[Populator_IPF_Plot]=])
    endif()
    if(_moos_test MATCHES [=[\.VPlugPlotTest\.]=])
      list(APPEND _moos_labels [=[VPlugPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorVPlugPlotsTest\.]=])
      list(APPEND _moos_labels [=[Populator_VPlugPlots]=])
    endif()
    if(_moos_test MATCHES [=[\.EncounterPlotTest\.]=])
      list(APPEND _moos_labels [=[EncounterPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorEncounterPlotTest\.]=])
      list(APPEND _moos_labels [=[Populator_EncounterPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.ALogDataBrokerTest\.]=])
      list(APPEND _moos_labels [=[ALogDataBroker]=])
    endif()
    if(_moos_test MATCHES [=[\.ModelVarScopeTest\.]=])
      list(APPEND _moos_labels [=[ModelVarScope]=])
    endif()
    if(_moos_test MATCHES [=[\.ModelHelmScopeTest\.]=])
      list(APPEND _moos_labels [=[ModelHelmScope]=])
    endif()
    if(_moos_test MATCHES [=[\.ModelAppLogScopeTest\.]=])
      list(APPEND _moos_labels [=[ModelAppLogScope]=])
    endif()
    if(_moos_test MATCHES [=[\.ModelTaskDiaryTest\.]=])
      list(APPEND _moos_labels [=[ModelTaskDiary]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
