if(DEFINED test_evalutil_vcheck_TESTS)
  foreach(_moos_test IN LISTS test_evalutil_vcheck_TESTS)
    set(_moos_labels [=[evalutil;pMissionEval]=])
    if(_moos_test MATCHES [=[\.VCheckTest\.]=])
      list(APPEND _moos_labels [=[VCheck]=])
    endif()
    if(_moos_test MATCHES [=[\.VCheckSetTest\.]=])
      list(APPEND _moos_labels [=[VCheckSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
