if(DEFINED test_bhvutil_refineries_TESTS)
  foreach(_moos_test IN LISTS test_bhvutil_refineries_TESTS)
    set(_moos_labels [=[bhvutil;BHV_AvoidCollision;BHV_AvoidObstacleV24]=])
    if(_moos_test MATCHES [=[\.RefineryCPATest\.]=])
      list(APPEND _moos_labels [=[RefineryCPA]=])
    endif()
    if(_moos_test MATCHES [=[\.RefineryObAvoidV24Test\.]=])
      list(APPEND _moos_labels [=[RefineryObAvoidV24]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
