if(DEFINED test_ivpbuild_zaic_TESTS)
  foreach(_moos_test IN LISTS test_ivpbuild_zaic_TESTS)
    set(_moos_labels [=[ivpbuild;math;ZAIC]=])
    if(_moos_test MATCHES [=[\.ZAICPeakTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_PEAK]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICSpeedTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_SPD]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICHeadingTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_HDG]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICHleqLeqHeqTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_LEQ]=])
      list(APPEND _moos_labels [=[ZAIC_HEQ]=])
      list(APPEND _moos_labels [=[ZAIC_HLEQ]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICVectorTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Vector]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
