if(DEFINED test_isay_speech_queue_TESTS)
  foreach(_moos_test IN LISTS test_isay_speech_queue_TESTS)
    set(_moos_labels [=[isay;SpeechQueue]=])
    if(_moos_test MATCHES [=[\.UtteranceTest\.]=])
      list(APPEND _moos_labels [=[Utterance]=])
    endif()
    if(_moos_test MATCHES [=[\.UtterQueueTest\.]=])
      list(APPEND _moos_labels [=[UtterQueue]=])
    endif()
    if(_moos_test MATCHES [=[\.SayerTest\.]=])
      list(APPEND _moos_labels [=[Sayer]=])
    endif()
    if(_moos_test MATCHES [=[\.VoiceUtilsTest\.]=])
      list(APPEND _moos_labels [=[VoiceUtils]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
