if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/isay/SpeechQueue/test_isay_speech_queue[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/isay/SpeechQueue/test_isay_speech_queue[1]_tests.cmake")
else()
  add_test(test_isay_speech_queue_NOT_BUILT test_isay_speech_queue_NOT_BUILT)
endif()
