if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/bhvutil/WaypointEngine/test_bhvutil_waypoint_engine[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/bhvutil/WaypointEngine/test_bhvutil_waypoint_engine[1]_tests.cmake")
else()
  add_test(test_bhvutil_waypoint_engine_NOT_BUILT test_bhvutil_waypoint_engine_NOT_BUILT)
endif()
