if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/logic/LogicCondition/test_logic_conditions[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/logic/LogicCondition/test_logic_conditions[1]_tests.cmake")
else()
  add_test(test_logic_conditions_NOT_BUILT test_logic_conditions_NOT_BUILT)
endif()
