if(DEFINED test_logic_conditions_TESTS)
  foreach(_moos_test IN LISTS test_logic_conditions_TESTS)
    set(_moos_labels [=[logic]=])
    if(_moos_test MATCHES [=[\.LogicConditionTest\.]=])
      list(APPEND _moos_labels [=[LogicCondition]=])
      list(APPEND _moos_labels [=[ParseNode]=])
    endif()
    if(_moos_test MATCHES [=[\.LogicUtilsTest\.]=])
      list(APPEND _moos_labels [=[LogicUtils]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
