if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogpick/PickHandler/test_alogpick_pick_handler[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogpick/PickHandler/test_alogpick_pick_handler[1]_tests.cmake")
else()
  add_test(test_alogpick_pick_handler_NOT_BUILT test_alogpick_pick_handler_NOT_BUILT)
endif()
