if(DEFINED test_geometry_xyconvexgrid_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyconvexgrid_TESTS)
    set(_moos_labels [=[geometry;grid;formats]=])
    if(_moos_test MATCHES [=[\.XYConvexGridTest\.]=])
      list(APPEND _moos_labels [=[XYConvexGrid]=])
    endif()
    if(_moos_test MATCHES [=[\.XYGridUpdateTest\.]=])
      list(APPEND _moos_labels [=[XYGridUpdate]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
