if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYConvexGrid/test_geometry_xyconvexgrid[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYConvexGrid/test_geometry_xyconvexgrid[1]_tests.cmake")
else()
  add_test(test_geometry_xyconvexgrid_NOT_BUILT test_geometry_xyconvexgrid_NOT_BUILT)
endif()
