if(DEFINED test_ufield_utils_TESTS)
  foreach(_moos_test IN LISTS test_ufield_utils_TESTS)
    set(_moos_labels [=[ufield;pShare]=])
    if(_moos_test MATCHES [=[\.UFieldUtilsTest\.]=])
      list(APPEND _moos_labels [=[UFieldUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.CommsEntryTest\.]=])
      list(APPEND _moos_labels [=[CommsEntry]=])
    endif()
    if(_moos_test MATCHES [=[\.CommsCatalogTest\.]=])
      list(APPEND _moos_labels [=[CommsCatalog]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
