if(DEFINED test_ivpbuild_pdmap_encoding_TESTS)
  foreach(_moos_test IN LISTS test_ivpbuild_pdmap_encoding_TESTS)
    set(_moos_labels [=[ivpbuild;math]=])
    if(_moos_test MATCHES [=[\.PDMapBuilderTest\.]=])
      list(APPEND _moos_labels [=[PDMapBuilder]=])
    endif()
    if(_moos_test MATCHES [=[\.FunctionEncoderTest\.]=])
      list(APPEND _moos_labels [=[FunctionEncoder]=])
    endif()
    if(_moos_test MATCHES [=[\.OFCouplerTest\.]=])
      list(APPEND _moos_labels [=[OF_Coupler]=])
    endif()
    if(_moos_test MATCHES [=[\.OFRaterTest\.]=])
      list(APPEND _moos_labels [=[OF_Rater]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
