if(DEFINED test_logutils_plot_data_TESTS)
  foreach(_moos_test IN LISTS test_logutils_plot_data_TESTS)
    set(_moos_labels [=[logutils]=])
    if(_moos_test MATCHES [=[\.LogPlotTest\.]=])
      list(APPEND _moos_labels [=[LogPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.VarPlotTest\.]=])
      list(APPEND _moos_labels [=[VarPlot]=])
    endif()
    if(_moos_test MATCHES [=[\.VarPlotEntryTest\.]=])
      list(APPEND _moos_labels [=[VarPlotEntry]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
