if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogpare/PareEngine/test_alogpare_pare_engine[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogpare/PareEngine/test_alogpare_pare_engine[1]_tests.cmake")
else()
  add_test(test_alogpare_pare_engine_NOT_BUILT test_alogpare_pare_engine_NOT_BUILT)
endif()
