if(DEFINED test_geometry_dubins_TESTS)
  foreach(_moos_test IN LISTS test_geometry_dubins_TESTS)
    set(_moos_labels [=[geometry;Dubins;math]=])
    if(_moos_test MATCHES [=[\.DubinsTurnTest\.]=])
      list(APPEND _moos_labels [=[DubinsTurn]=])
    endif()
    if(_moos_test MATCHES [=[\.DubinsTurnWallLookaheadTest\.]=])
      list(APPEND _moos_labels [=[DubinsTurn]=])
    endif()
    if(_moos_test MATCHES [=[\.DubinsCacheValidationTest\.]=])
      list(APPEND _moos_labels [=[DubinsCache]=])
    endif()
    if(_moos_test MATCHES [=[\.DubinsCacheQuirkTest\.]=])
      list(APPEND _moos_labels [=[DubinsCache]=])
    endif()
    if(_moos_test MATCHES [=[\.DubinsCacheLookupTest\.]=])
      list(APPEND _moos_labels [=[DubinsCache]=])
    endif()
    if(_moos_test MATCHES [=[\.DubinsCacheInvalidQueryTest\.]=])
      list(APPEND _moos_labels [=[DubinsCache]=])
    endif()
    if(_moos_test MATCHES [=[\.DubinsCacheMaxTurnTest\.]=])
      list(APPEND _moos_labels [=[DubinsCache]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
