if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogsort/SortHandler/test_alogsort_sort_handler[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogsort/SortHandler/test_alogsort_sort_handler[1]_tests.cmake")
else()
  add_test(test_alogsort_sort_handler_NOT_BUILT test_alogsort_sort_handler_NOT_BUILT)
endif()
