if(DEFINED test_manifest_core_TESTS)
  foreach(_moos_test IN LISTS test_manifest_core_TESTS)
    set(_moos_labels [=[manifest]=])
    if(_moos_test MATCHES [=[\.ManifestTest\.]=])
      list(APPEND _moos_labels [=[Manifest]=])
    endif()
    if(_moos_test MATCHES [=[\.ManifestSetTest\.]=])
      list(APPEND _moos_labels [=[ManifestSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
