if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/manifest/Core/test_manifest_core[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/manifest/Core/test_manifest_core[1]_tests.cmake")
else()
  add_test(test_manifest_core_NOT_BUILT test_manifest_core_NOT_BUILT)
endif()
