if(DEFINED test_ufldbeaconrangesensor_beacon_buoy_TESTS)
  foreach(_moos_test IN LISTS test_ufldbeaconrangesensor_beacon_buoy_TESTS)
    set(_moos_labels [=[ufldbeaconrangesensor;BeaconBuoy]=])
    if(_moos_test MATCHES [=[\.BeaconBuoyTest\.]=])
      list(APPEND _moos_labels [=[BeaconBuoy]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
