if(DEFINED test_apputil_appcast_TESTS)
  foreach(_moos_test IN LISTS test_apputil_appcast_TESTS)
    set(_moos_labels [=[apputil]=])
    if(_moos_test MATCHES [=[\.AppCastSetTest\.]=])
      list(APPEND _moos_labels [=[AppCastSet]=])
    endif()
    if(_moos_test MATCHES [=[\.AppCastTreeTest\.]=])
      list(APPEND _moos_labels [=[AppCastTree]=])
    endif()
    if(_moos_test MATCHES [=[\.AppCastRepoTest\.]=])
      list(APPEND _moos_labels [=[AppCastRepo]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
