if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogcd/CollisionReporter/test_alogcd_collision_reporter[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogcd/CollisionReporter/test_alogcd_collision_reporter[1]_tests.cmake")
else()
  add_test(test_alogcd_collision_reporter_NOT_BUILT test_alogcd_collision_reporter_NOT_BUILT)
endif()
