if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/zaicview/Core/test_zaicview_models[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/zaicview/Core/test_zaicview_models[1]_tests.cmake")
else()
  add_test(test_zaicview_models_NOT_BUILT test_zaicview_models_NOT_BUILT)
endif()
