if(DEFINED test_zaicview_gui_TESTS)
  foreach(_moos_test IN LISTS test_zaicview_gui_TESTS)
    set(_moos_labels [=[zaicview;gui;requires_fltk;requires_opengl]=])
    if(_moos_test MATCHES [=[\.ZAICViewerTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Viewer]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICGUITest\.]=])
      list(APPEND _moos_labels [=[ZAIC_GUI]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
