if(DEFINED test_zaicview_models_TESTS)
  foreach(_moos_test IN LISTS test_zaicview_models_TESTS)
    set(_moos_labels [=[zaicview]=])
    if(_moos_test MATCHES [=[\.ZAICModelTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Model]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICHDGModelTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Model]=])
      list(APPEND _moos_labels [=[ZAIC_HDG_Model]=])
      list(APPEND _moos_labels [=[zaic_hdg]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICSPDModelTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Model]=])
      list(APPEND _moos_labels [=[ZAIC_SPD_Model]=])
      list(APPEND _moos_labels [=[zaic_spd]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICHLEQModelTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Model]=])
      list(APPEND _moos_labels [=[ZAIC_HLEQ_Model]=])
      list(APPEND _moos_labels [=[zaic_hleq]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICPEAKModelTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Model]=])
      list(APPEND _moos_labels [=[ZAIC_PEAK_Model]=])
      list(APPEND _moos_labels [=[zaic_peak]=])
    endif()
    if(_moos_test MATCHES [=[\.ZAICVectModelTest\.]=])
      list(APPEND _moos_labels [=[ZAIC_Model]=])
      list(APPEND _moos_labels [=[ZAIC_VECT_Model]=])
      list(APPEND _moos_labels [=[PopulatorVZAIC]=])
      list(APPEND _moos_labels [=[zaic_vect]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
