if(DEFINED test_pechovar_eflipper_TESTS)
  foreach(_moos_test IN LISTS test_pechovar_eflipper_TESTS)
    set(_moos_labels [=[pechovar;EFlipper]=])
    if(_moos_test MATCHES [=[\.EFlipperTest\.]=])
      list(APPEND _moos_labels [=[EFlipper]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
