if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/pechovar/EFlipper/test_pechovar_eflipper[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/pechovar/EFlipper/test_pechovar_eflipper[1]_tests.cmake")
else()
  add_test(test_pechovar_eflipper_NOT_BUILT test_pechovar_eflipper_NOT_BUILT)
endif()
