if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/apputil/Formatting/test_apputil_formatting[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/apputil/Formatting/test_apputil_formatting[1]_tests.cmake")
else()
  add_test(test_apputil_formatting_NOT_BUILT test_apputil_formatting_NOT_BUILT)
endif()
