if(DEFINED test_apputil_formatting_TESTS)
  foreach(_moos_test IN LISTS test_apputil_formatting_TESTS)
    set(_moos_labels [=[apputil;AppCastFormatting]=])
    if(_moos_test MATCHES [=[\.ACTableTest\.]=])
      list(APPEND _moos_labels [=[ACTable]=])
    endif()
    if(_moos_test MATCHES [=[\.ACBlockTest\.]=])
      list(APPEND _moos_labels [=[ACBlock]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
