if(DEFINED test_logic_infobuffer_TESTS)
  foreach(_moos_test IN LISTS test_logic_infobuffer_TESTS)
    set(_moos_labels [=[logic]=])
    if(_moos_test MATCHES [=[\.InfoBufferTest\.]=])
      list(APPEND _moos_labels [=[InfoBuffer]=])
    endif()
    if(_moos_test MATCHES [=[\.LogicBufferTest\.]=])
      list(APPEND _moos_labels [=[LogicBuffer]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
