if(DEFINED test_geometry_cpaplatform_TESTS)
  foreach(_moos_test IN LISTS test_geometry_cpaplatform_TESTS)
    set(_moos_labels [=[geometry;CPAPlatform;math]=])
    if(_moos_test MATCHES [=[\.BNGEngineTest\.]=])
      list(APPEND _moos_labels [=[BNGEngine]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAUtilsEvalCPATest\.]=])
      list(APPEND _moos_labels [=[CPA_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAUtilsCrossesBowTest\.]=])
      list(APPEND _moos_labels [=[CPA_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAUtilsClosingSpeedTest\.]=])
      list(APPEND _moos_labels [=[CPA_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAUtilsVelocityVectorSumTest\.]=])
      list(APPEND _moos_labels [=[CPA_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAUtilsRelAngRateTest\.]=])
      list(APPEND _moos_labels [=[CPA_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.PlatModelPoseTest\.]=])
      list(APPEND _moos_labels [=[PlatModel]=])
    endif()
    if(_moos_test MATCHES [=[\.PlatModelParseTest\.]=])
      list(APPEND _moos_labels [=[PlatModel]=])
    endif()
    if(_moos_test MATCHES [=[\.PlatModelSpokeTest\.]=])
      list(APPEND _moos_labels [=[PlatModel]=])
    endif()
    if(_moos_test MATCHES [=[\.PlatModelTurnSeglrTest\.]=])
      list(APPEND _moos_labels [=[PlatModel]=])
    endif()
    if(_moos_test MATCHES [=[\.PlatModelCacheTest\.]=])
      list(APPEND _moos_labels [=[PlatModel]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
