if(DEFINED test_behaviors_life_events_TESTS)
  foreach(_moos_test IN LISTS test_behaviors_life_events_TESTS)
    set(_moos_labels [=[behaviors;pHelmIvP]=])
    if(_moos_test MATCHES [=[\.LifeEventTest\.]=])
      list(APPEND _moos_labels [=[LifeEvent]=])
    endif()
    if(_moos_test MATCHES [=[\.LifeEventHistoryTest\.]=])
      list(APPEND _moos_labels [=[LifeEventHistory]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
