if(DEFINED test_behaviors_core_state_TESTS)
  foreach(_moos_test IN LISTS test_behaviors_core_state_TESTS)
    set(_moos_labels [=[behaviors;pHelmIvP]=])
    if(_moos_test MATCHES [=[\.ContactStateTest\.]=])
      list(APPEND _moos_labels [=[ContactState]=])
    endif()
    if(_moos_test MATCHES [=[\.ContactStateSetTest\.]=])
      list(APPEND _moos_labels [=[ContactStateSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
