if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/marine_pid/PIDEngine/test_marine_pid_pid_engine[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/marine_pid/PIDEngine/test_marine_pid_pid_engine[1]_tests.cmake")
else()
  add_test(test_marine_pid_pid_engine_NOT_BUILT test_marine_pid_pid_engine_NOT_BUILT)
endif()
