if(DEFINED test_marine_pid_pid_engine_TESTS)
  foreach(_moos_test IN LISTS test_marine_pid_pid_engine_TESTS)
    set(_moos_labels [=[marine_pid;pMarinePIDV22]=])
    if(_moos_test MATCHES [=[\.ScalarPIDTest\.]=])
      list(APPEND _moos_labels [=[ScalarPID]=])
    endif()
    if(_moos_test MATCHES [=[\.PIDEngineConfigTest\.]=])
      list(APPEND _moos_labels [=[PIDEngine]=])
    endif()
    if(_moos_test MATCHES [=[\.PIDEngineDiagnosticsTest\.]=])
      list(APPEND _moos_labels [=[PIDEngine]=])
    endif()
    if(_moos_test MATCHES [=[\.PIDEngineOutputTest\.]=])
      list(APPEND _moos_labels [=[PIDEngine]=])
    endif()
    if(_moos_test MATCHES [=[\.PIDEngineOverrideTest\.]=])
      list(APPEND _moos_labels [=[PIDEngine]=])
    endif()
    if(_moos_test MATCHES [=[\.PIDEnginePostingsTest\.]=])
      list(APPEND _moos_labels [=[PIDEngine]=])
    endif()
    if(_moos_test MATCHES [=[\.PIDEngineStalenessTest\.]=])
      list(APPEND _moos_labels [=[PIDEngine]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
