if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/evalutil/LogicTestSequence/test_evalutil_logic_sequence[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/evalutil/LogicTestSequence/test_evalutil_logic_sequence[1]_tests.cmake")
else()
  add_test(test_evalutil_logic_sequence_NOT_BUILT test_evalutil_logic_sequence_NOT_BUILT)
endif()
