if(DEFINED test_evalutil_logic_sequence_TESTS)
  foreach(_moos_test IN LISTS test_evalutil_logic_sequence_TESTS)
    set(_moos_labels [=[evalutil;pMissionEval]=])
    if(_moos_test MATCHES [=[\.LogicAspectTest\.]=])
      list(APPEND _moos_labels [=[LogicAspect]=])
    endif()
    if(_moos_test MATCHES [=[\.LogicTestSequenceTest\.]=])
      list(APPEND _moos_labels [=[LogicTestSequence]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
