if(DEFINED test_utimerscript_random_script_TESTS)
  foreach(_moos_test IN LISTS test_utimerscript_random_script_TESTS)
    set(_moos_labels [=[utimerscript;RandomScript]=])
    if(_moos_test MATCHES [=[\.EnumVariableTest\.]=])
      list(APPEND _moos_labels [=[EnumVariable]=])
    endif()
    if(_moos_test MATCHES [=[\.RandPairPolyTest\.]=])
      list(APPEND _moos_labels [=[RandPairPoly]=])
    endif()
    if(_moos_test MATCHES [=[\.RandomPairSetTest\.]=])
      list(APPEND _moos_labels [=[RandomPairSet]=])
    endif()
    if(_moos_test MATCHES [=[\.RandomPairTest\.]=])
      list(APPEND _moos_labels [=[RandomPair]=])
    endif()
    if(_moos_test MATCHES [=[\.RandomVariableSetTest\.]=])
      list(APPEND _moos_labels [=[RandomVariableSet]=])
    endif()
    if(_moos_test MATCHES [=[\.RandVarGaussianTest\.]=])
      list(APPEND _moos_labels [=[RandVarGaussian]=])
    endif()
    if(_moos_test MATCHES [=[\.RandVarUniformTest\.]=])
      list(APPEND _moos_labels [=[RandVarUniform]=])
    endif()
    if(_moos_test MATCHES [=[\.TS_MOOSAppEventTest\.]=])
      list(APPEND _moos_labels [=[TS_MOOSApp]=])
    endif()
    if(_moos_test MATCHES [=[\.TS_MOOSAppMathTest\.]=])
      list(APPEND _moos_labels [=[TS_MOOSApp]=])
    endif()
    if(_moos_test MATCHES [=[\.TS_MOOSAppUtilityTest\.]=])
      list(APPEND _moos_labels [=[TS_MOOSApp]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
