if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/CircularUtils/test_geometry_circularutils[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/CircularUtils/test_geometry_circularutils[1]_tests.cmake")
else()
  add_test(test_geometry_circularutils_NOT_BUILT test_geometry_circularutils_NOT_BUILT)
endif()
