if(DEFINED test_geometry_polygon_generation_TESTS)
  foreach(_moos_test IN LISTS test_geometry_polygon_generation_TESTS)
    set(_moos_labels [=[geometry;polygon_generation]=])
    if(_moos_test MATCHES [=[\.ConvexHullGeneratorTest\.]=])
      list(APPEND _moos_labels [=[ConvexHullGenerator]=])
    endif()
    if(_moos_test MATCHES [=[\.XYPolyExpanderTest\.]=])
      list(APPEND _moos_labels [=[XYPolyExpander]=])
    endif()
    if(_moos_test MATCHES [=[\.XYPatternBlockTest\.]=])
      list(APPEND _moos_labels [=[XYPatternBlock]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
