if(DEFINED test_survey_generators_TESTS)
  foreach(_moos_test IN LISTS test_survey_generators_TESTS)
    set(_moos_labels [=[survey;pMarineViewer;SURVEY_UPDATES]=])
    if(_moos_test MATCHES [=[\.RectHullGeneratorTest\.]=])
      list(APPEND _moos_labels [=[RectHullGenerator]=])
    endif()
    if(_moos_test MATCHES [=[\.SurveyGeneratorTest\.]=])
      list(APPEND _moos_labels [=[SurveyGenerator]=])
      list(APPEND _moos_labels [=[XYPatternBlock]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
