if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/survey/SurveyGenerators/test_survey_generators[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/survey/SurveyGenerators/test_survey_generators[1]_tests.cmake")
else()
  add_test(test_survey_generators_NOT_BUILT test_survey_generators_NOT_BUILT)
endif()
