if(DEFINED test_helmivp_core_state_TESTS)
  foreach(_moos_test IN LISTS test_helmivp_core_state_TESTS)
    set(_moos_labels [=[helmivp;pHelmIvP]=])
    if(_moos_test MATCHES [=[\.ModeEntryTest\.]=])
      list(APPEND _moos_labels [=[ModeEntry]=])
    endif()
    if(_moos_test MATCHES [=[\.ModeSetTest\.]=])
      list(APPEND _moos_labels [=[ModeSet]=])
    endif()
    if(_moos_test MATCHES [=[\.BehaviorReportTest\.]=])
      list(APPEND _moos_labels [=[BehaviorReport]=])
    endif()
    if(_moos_test MATCHES [=[\.BehaviorSpecTest\.]=])
      list(APPEND _moos_labels [=[BehaviorSpec]=])
    endif()
    if(_moos_test MATCHES [=[\.HelmReportTest\.]=])
      list(APPEND _moos_labels [=[HelmReport]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
