if(DEFINED test_geometry_xyviewer_shapes_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyviewer_shapes_TESTS)
    set(_moos_labels [=[geometry;XYViewerShapes;viewer_shapes;formats]=])
    if(_moos_test MATCHES [=[\.XYOvalTest\.]=])
      list(APPEND _moos_labels [=[XYOval]=])
      list(APPEND _moos_labels [=[VPlug_GeoShapes]=])
    endif()
    if(_moos_test MATCHES [=[\.XYTextBoxTest\.]=])
      list(APPEND _moos_labels [=[XYTextBox]=])
      list(APPEND _moos_labels [=[VPlug_GeoShapes]=])
    endif()
    if(_moos_test MATCHES [=[\.XYVesselTest\.]=])
      list(APPEND _moos_labels [=[XYVessel]=])
      list(APPEND _moos_labels [=[VPlug_GeoShapes]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
