if(DEFINED test_geometry_objectbasebuild_TESTS)
  foreach(_moos_test IN LISTS test_geometry_objectbasebuild_TESTS)
    set(_moos_labels [=[geometry;ObjectBaseBuild;object_base;build_utils;viewer_metadata]=])
    if(_moos_test MATCHES [=[\.XYObjectTest\.]=])
      list(APPEND _moos_labels [=[XYObject]=])
    endif()
    if(_moos_test MATCHES [=[\.XYBuildUtilsTest\.]=])
      list(APPEND _moos_labels [=[XYBuildUtils]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
