if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/ObjectBaseBuild/test_geometry_objectbasebuild[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/ObjectBaseBuild/test_geometry_objectbasebuild[1]_tests.cmake")
else()
  add_test(test_geometry_objectbasebuild_NOT_BUILT test_geometry_objectbasebuild_NOT_BUILT)
endif()
