if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYPrimitiveShapes/test_geometry_xyprimitive_shapes[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYPrimitiveShapes/test_geometry_xyprimitive_shapes[1]_tests.cmake")
else()
  add_test(test_geometry_xyprimitive_shapes_NOT_BUILT test_geometry_xyprimitive_shapes_NOT_BUILT)
endif()
