if(DEFINED test_geometry_xyprimitive_shapes_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyprimitive_shapes_TESTS)
    set(_moos_labels [=[geometry;math;XYPrimitiveShapes;primitive_shapes]=])
    if(_moos_test MATCHES [=[\.XYArrowPrimitiveTest\.]=])
      list(APPEND _moos_labels [=[XYArrow]=])
    endif()
    if(_moos_test MATCHES [=[\.VPlugGeoShapesPrimitiveVectorTest\.]=])
      list(APPEND _moos_labels [=[VPlug_GeoShapes]=])
    endif()
    if(_moos_test MATCHES [=[\.XYSegmentPrimitiveTest\.]=])
      list(APPEND _moos_labels [=[XYSegment]=])
    endif()
    if(_moos_test MATCHES [=[\.XYSquarePrimitiveTest\.]=])
      list(APPEND _moos_labels [=[XYSquare]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
