if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYFormatUtilsCircle/test_geometry_xyformatutils_circle[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/XYFormatUtilsCircle/test_geometry_xyformatutils_circle[1]_tests.cmake")
else()
  add_test(test_geometry_xyformatutils_circle_NOT_BUILT test_geometry_xyformatutils_circle_NOT_BUILT)
endif()
