if(DEFINED test_geometry_xyformatutils_circle_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_circle_TESTS)
    set(_moos_labels [=[geometry;formats]=])
    if(_moos_test MATCHES [=[\.XYCircleTest\.]=])
      list(APPEND _moos_labels [=[XYCircle]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsCircleTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsCircle]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
