if(DEFINED test_turngeo_turn_generator_TESTS)
  foreach(_moos_test IN LISTS test_turngeo_turn_generator_TESTS)
    set(_moos_labels [=[turngeo;LegRun]=])
    if(_moos_test MATCHES [=[\.TurnGeneratorTest\.]=])
      list(APPEND _moos_labels [=[TurnGenerator]=])
    endif()
    if(_moos_test MATCHES [=[\.TurnGen180Test\.]=])
      list(APPEND _moos_labels [=[TurnGen180]=])
    endif()
    if(_moos_test MATCHES [=[\.TurnGenWilliamsonTest\.]=])
      list(APPEND _moos_labels [=[TurnGenWilliamson]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
