if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/turngeo/TurnGenerator/test_turngeo_turn_generator[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/turngeo/TurnGenerator/test_turngeo_turn_generator[1]_tests.cmake")
else()
  add_test(test_turngeo_turn_generator_NOT_BUILT test_turngeo_turn_generator_NOT_BUILT)
endif()
