if(DEFINED test_helmivp_behavior_loading_TESTS)
  foreach(_moos_test IN LISTS test_helmivp_behavior_loading_TESTS)
    set(_moos_labels [=[helmivp;pHelmIvP]=])
    if(_moos_test MATCHES [=[\.BFactoryStaticTest\.]=])
      list(APPEND _moos_labels [=[BFactoryStatic]=])
    endif()
    if(_moos_test MATCHES [=[\.BFactoryDynamicTest\.]=])
      list(APPEND _moos_labels [=[BFactoryDynamic]=])
    endif()
    if(_moos_test MATCHES [=[\.SpecBuildTest\.]=])
      list(APPEND _moos_labels [=[SpecBuild]=])
    endif()
    if(_moos_test MATCHES [=[\.BehaviorSetTest\.]=])
      list(APPEND _moos_labels [=[BehaviorSet]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorBehaviorSetTest\.]=])
      list(APPEND _moos_labels [=[Populator_BehaviorSet]=])
    endif()
    if(_moos_test MATCHES [=[\.PlatformModelGeneratorTest\.]=])
      list(APPEND _moos_labels [=[PMGen]=])
      list(APPEND _moos_labels [=[PlatModelGenerator]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
