if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/helmivp/FactoryPopulation/test_helmivp_behavior_loading[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/helmivp/FactoryPopulation/test_helmivp_behavior_loading[1]_tests.cmake")
else()
  add_test(test_helmivp_behavior_loading_NOT_BUILT test_helmivp_behavior_loading_NOT_BUILT)
endif()
