if(DEFINED test_ivpbuild_reflector_internals_TESTS)
  foreach(_moos_test IN LISTS test_ivpbuild_reflector_internals_TESTS)
    set(_moos_labels [=[ivpbuild;pHelmIvP;uFunctionVis]=])
    if(_moos_test MATCHES [=[\.BuildUtilsTest\.]=])
      list(APPEND _moos_labels [=[BuildUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.BuildUtilsBetaTest\.]=])
      list(APPEND _moos_labels [=[BuildUtilsBeta]=])
    endif()
    if(_moos_test MATCHES [=[\.DemuxUnitTest\.]=])
      list(APPEND _moos_labels [=[DemuxUnit]=])
      list(APPEND _moos_labels [=[DemuxedResult]=])
    endif()
    if(_moos_test MATCHES [=[\.DemuxerTest\.]=])
      list(APPEND _moos_labels [=[Demuxer]=])
    endif()
    if(_moos_test MATCHES [=[\.FunctionEncoderMKTest\.]=])
      list(APPEND _moos_labels [=[FunctionEncoderMK]=])
    endif()
    if(_moos_test MATCHES [=[\.IOUtilitiesTest\.]=])
      list(APPEND _moos_labels [=[IO_Utilities]=])
    endif()
    if(_moos_test MATCHES [=[\.PQueueTest\.]=])
      list(APPEND _moos_labels [=[PQueue]=])
    endif()
    if(_moos_test MATCHES [=[\.RegressorTest\.]=])
      list(APPEND _moos_labels [=[Regressor]=])
    endif()
    if(_moos_test MATCHES [=[\.ReflectorToolsTest\.]=])
      list(APPEND _moos_labels [=[RT_Uniform]=])
      list(APPEND _moos_labels [=[RT_UniformX]=])
      list(APPEND _moos_labels [=[RT_Directed]=])
      list(APPEND _moos_labels [=[RT_Evaluator]=])
      list(APPEND _moos_labels [=[RT_Smart]=])
      list(APPEND _moos_labels [=[RT_AutoPeak]=])
    endif()
    if(_moos_test MATCHES [=[\.OFReflectorTest\.]=])
      list(APPEND _moos_labels [=[OF_Reflector]=])
      list(APPEND _moos_labels [=[RT_Uniform]=])
      list(APPEND _moos_labels [=[RT_UniformX]=])
      list(APPEND _moos_labels [=[RT_Directed]=])
      list(APPEND _moos_labels [=[RT_Evaluator]=])
      list(APPEND _moos_labels [=[RT_Smart]=])
      list(APPEND _moos_labels [=[RT_AutoPeak]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
