if(DEFINED test_geometry_xyformatutils_wedge_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_wedge_TESTS)
    set(_moos_labels [=[geometry;formats]=])
    if(_moos_test MATCHES [=[\.XYWedgeTest\.]=])
      list(APPEND _moos_labels [=[XYWedge]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsWedgeTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsWedge]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
