if(DEFINED test_marineview_backimg_TESTS)
  foreach(_moos_test IN LISTS test_marineview_backimg_TESTS)
    set(_moos_labels [=[marineview;pMarineViewer;requires_tiff;requires_opengl]=])
    if(_moos_test MATCHES [=[\.BackImgTest\.]=])
      list(APPEND _moos_labels [=[BackImg]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
