if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/marineview/Core/test_marineview_gui[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/marineview/Core/test_marineview_gui[1]_tests.cmake")
else()
  add_test(test_marineview_gui_NOT_BUILT test_marineview_gui_NOT_BUILT)
endif()
