if(DEFINED test_marineview_gui_TESTS)
  foreach(_moos_test IN LISTS test_marineview_gui_TESTS)
    set(_moos_labels [=[marineview;pMarineViewer;gui;requires_tiff;requires_fltk;requires_opengl]=])
    if(_moos_test MATCHES [=[\.MarineViewerTest\.]=])
      list(APPEND _moos_labels [=[MarineViewer]=])
    endif()
    if(_moos_test MATCHES [=[\.MarineGUITest\.]=])
      list(APPEND _moos_labels [=[MarineGUI]=])
      list(APPEND _moos_labels [=[MarineViewWidgets]=])
    endif()
    if(_moos_test MATCHES [=[\.MarineVehiGUITest\.]=])
      list(APPEND _moos_labels [=[MarineVehiGUI]=])
      list(APPEND _moos_labels [=[MarineViewWidgets]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
