if(DEFINED test_marineview_core_TESTS)
  foreach(_moos_test IN LISTS test_marineview_core_TESTS)
    set(_moos_labels [=[marineview;pMarineViewer]=])
    if(_moos_test MATCHES [=[\.BearingLineTest\.]=])
      list(APPEND _moos_labels [=[BearingLine]=])
    endif()
    if(_moos_test MATCHES [=[\.LMVUtilsTest\.]=])
      list(APPEND _moos_labels [=[LMV_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.OpAreaSpecTest\.]=])
      list(APPEND _moos_labels [=[OpAreaSpec]=])
    endif()
    if(_moos_test MATCHES [=[\.VehicleSetTest\.]=])
      list(APPEND _moos_labels [=[VehicleSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
