if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/GeoShapesLifecycle/test_geometry_geoshapes_lifecycle[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/GeoShapesLifecycle/test_geometry_geoshapes_lifecycle[1]_tests.cmake")
else()
  add_test(test_geometry_geoshapes_lifecycle_NOT_BUILT test_geometry_geoshapes_lifecycle_NOT_BUILT)
endif()
