if(DEFINED test_geometry_cpavariants_TESTS)
  foreach(_moos_test IN LISTS test_geometry_cpavariants_TESTS)
    set(_moos_labels [=[geometry;CPAVariants;CPAEngine;math]=])
    if(_moos_test MATCHES [=[\.CPAEngineRootVariantTest\.]=])
      list(APPEND _moos_labels [=[CPAEngineRoot]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAModernThinEquivalenceTest\.]=])
      list(APPEND _moos_labels [=[CPAEngineThin]=])
      list(APPEND _moos_labels [=[CPAEngineV15]=])
    endif()
    if(_moos_test MATCHES [=[\.CPABowSternGeometryTest\.]=])
      list(APPEND _moos_labels [=[CPAEngineThin]=])
      list(APPEND _moos_labels [=[CPAEngineV15]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAPassGeometryTest\.]=])
      list(APPEND _moos_labels [=[CPAEngineThin]=])
      list(APPEND _moos_labels [=[CPAEngineV15]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAEngineThinVariantTest\.]=])
      list(APPEND _moos_labels [=[CPAEngineThin]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAEngineV15VariantTest\.]=])
      list(APPEND _moos_labels [=[CPAEngineV15]=])
    endif()
    if(_moos_test MATCHES [=[\.CPAEngineVariantEdgeCaseTest\.]=])
      list(APPEND _moos_labels [=[CPAEngineThin]=])
      list(APPEND _moos_labels [=[CPAEngineV15]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
