if(DEFINED test_geodaid_contact_ledger_TESTS)
  foreach(_moos_test IN LISTS test_geodaid_contact_ledger_TESTS)
    set(_moos_labels [=[geodaid;NodeReport;pHelmIvP;pContactMgrV20;pMarineViewer]=])
    if(_moos_test MATCHES [=[\.ContactLedgerTest\.]=])
      list(APPEND _moos_labels [=[ContactLedger]=])
    endif()
    if(_moos_test MATCHES [=[\.ColoredPointTest\.]=])
      list(APPEND _moos_labels [=[ColoredPoint]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
