if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geodaid/ContactLedger/test_geodaid_contact_ledger[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geodaid/ContactLedger/test_geodaid_contact_ledger[1]_tests.cmake")
else()
  add_test(test_geodaid_contact_ledger_NOT_BUILT test_geodaid_contact_ledger_NOT_BUILT)
endif()
