if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/prealm/PipeWay/test_prealm_pipeway[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/prealm/PipeWay/test_prealm_pipeway[1]_tests.cmake")
else()
  add_test(test_prealm_pipeway_NOT_BUILT test_prealm_pipeway_NOT_BUILT)
endif()
