if(DEFINED test_prealm_pipeway_TESTS)
  foreach(_moos_test IN LISTS test_prealm_pipeway_TESTS)
    set(_moos_labels [=[prealm;PipeWay]=])
    if(_moos_test MATCHES [=[\.PipeWayTest\.]=])
      list(APPEND _moos_labels [=[PipeWay]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
