if(DEFINED test_geometry_io_and_populators_TESTS)
  foreach(_moos_test IN LISTS test_geometry_io_and_populators_TESTS)
    set(_moos_labels [=[geometry;IOAndPopulators;files;populators]=])
    if(_moos_test MATCHES [=[\.IOGeomUtilsPolyStringFileTest\.]=])
      list(APPEND _moos_labels [=[IO_GeomUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.IOGeomUtilsPolyFileTest\.]=])
      list(APPEND _moos_labels [=[IO_GeomUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.IOGeomUtilsShapeFileTest\.]=])
      list(APPEND _moos_labels [=[IO_GeomUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.IOGeomUtilsGridFileTest\.]=])
      list(APPEND _moos_labels [=[IO_GeomUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.IOGeomUtilsOutputTest\.]=])
      list(APPEND _moos_labels [=[IO_GeomUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.OpFieldPointTest\.]=])
      list(APPEND _moos_labels [=[OpField]=])
    endif()
    if(_moos_test MATCHES [=[\.OpFieldPolyTest\.]=])
      list(APPEND _moos_labels [=[OpField]=])
    endif()
    if(_moos_test MATCHES [=[\.OpFieldConfigTest\.]=])
      list(APPEND _moos_labels [=[OpField]=])
    endif()
    if(_moos_test MATCHES [=[\.OpFieldMergeAndSimplifyTest\.]=])
      list(APPEND _moos_labels [=[OpField]=])
    endif()
    if(_moos_test MATCHES [=[\.PopulatorOpFieldFileTest\.]=])
      list(APPEND _moos_labels [=[Populator_OpField]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
