if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/IOAndPopulators/test_geometry_io_and_populators[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/IOAndPopulators/test_geometry_io_and_populators[1]_tests.cmake")
else()
  add_test(test_geometry_io_and_populators_NOT_BUILT test_geometry_io_and_populators_NOT_BUILT)
endif()
