if(DEFINED test_logic_conditional_ledger_TESTS)
  foreach(_moos_test IN LISTS test_logic_conditional_ledger_TESTS)
    set(_moos_labels [=[logic]=])
    if(_moos_test MATCHES [=[\.ConditionalParamTest\.]=])
      list(APPEND _moos_labels [=[ConditionalParam]=])
    endif()
    if(_moos_test MATCHES [=[\.LedgerSnapTest\.]=])
      list(APPEND _moos_labels [=[LedgerSnap]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
