if(DEFINED test_geometry_xyformatutils_pulse_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_pulse_TESTS)
    set(_moos_labels [=[geometry;formats;XYFormatUtilsPulse;pulse]=])
    if(_moos_test MATCHES [=[\.XYFormatUtilsRangePulseTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsRangePulse]=])
    endif()
    if(_moos_test MATCHES [=[\.XYRangePulseTest\.]=])
      list(APPEND _moos_labels [=[XYRangePulse]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsCommsPulseTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsCommsPulse]=])
    endif()
    if(_moos_test MATCHES [=[\.XYCommsPulseTest\.]=])
      list(APPEND _moos_labels [=[XYCommsPulse]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
