if(DEFINED test_uhelmscope_helm_records_TESTS)
  foreach(_moos_test IN LISTS test_uhelmscope_helm_records_TESTS)
    set(_moos_labels [=[uhelmscope;HelmRecords]=])
    if(_moos_test MATCHES [=[\.BehaviorRecordTest\.]=])
      list(APPEND _moos_labels [=[BehaviorRecord]=])
    endif()
    if(_moos_test MATCHES [=[\.IterBlockHelmTest\.]=])
      list(APPEND _moos_labels [=[IterBlockHelm]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
