if(DEFINED test_geometry_trackproximity_TESTS)
  foreach(_moos_test IN LISTS test_geometry_trackproximity_TESTS)
    set(_moos_labels [=[geometry;TrackProximity;math]=])
    if(_moos_test MATCHES [=[\.LinearExtrapolatorStateTest\.]=])
      list(APPEND _moos_labels [=[LinearExtrapolator]=])
    endif()
    if(_moos_test MATCHES [=[\.LinearExtrapolatorMotionTest\.]=])
      list(APPEND _moos_labels [=[LinearExtrapolator]=])
    endif()
    if(_moos_test MATCHES [=[\.LinearExtrapolatorTimeTest\.]=])
      list(APPEND _moos_labels [=[LinearExtrapolator]=])
    endif()
    if(_moos_test MATCHES [=[\.LinearExtrapolatorDecayTest\.]=])
      list(APPEND _moos_labels [=[LinearExtrapolator]=])
    endif()
    if(_moos_test MATCHES [=[\.LinearExtrapolatorMoosUseTest\.]=])
      list(APPEND _moos_labels [=[LinearExtrapolator]=])
    endif()
    if(_moos_test MATCHES [=[\.WrapDetectorStateTest\.]=])
      list(APPEND _moos_labels [=[WrapDetector]=])
    endif()
    if(_moos_test MATCHES [=[\.WrapDetectorWrapTest\.]=])
      list(APPEND _moos_labels [=[WrapDetector]=])
    endif()
    if(_moos_test MATCHES [=[\.WrapDetectorHistoryTest\.]=])
      list(APPEND _moos_labels [=[WrapDetector]=])
    endif()
    if(_moos_test MATCHES [=[\.ProxPointStateTest\.]=])
      list(APPEND _moos_labels [=[ProxPoint]=])
    endif()
    if(_moos_test MATCHES [=[\.ProxPointOrderingTest\.]=])
      list(APPEND _moos_labels [=[ProxPoint]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
