if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/behaviors_marine/CoreBehaviors/test_behaviors_marine_avoid_collision[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/behaviors_marine/CoreBehaviors/test_behaviors_marine_avoid_collision[1]_tests.cmake")
else()
  add_test(test_behaviors_marine_avoid_collision_NOT_BUILT test_behaviors_marine_avoid_collision_NOT_BUILT)
endif()
