if(DEFINED test_obstacles_obstacle_TESTS)
  foreach(_moos_test IN LISTS test_obstacles_obstacle_TESTS)
    set(_moos_labels [=[obstacles;uFldObstacleMgr]=])
    if(_moos_test MATCHES [=[\.ObstacleTest\.]=])
      list(APPEND _moos_labels [=[Obstacle]=])
    endif()
    if(_moos_test MATCHES [=[\.ObstacleFieldGeneratorTest\.]=])
      list(APPEND _moos_labels [=[ObstacleFieldGenerator]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
