if(DEFINED test_geometry_xyformatutils_segl_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_segl_TESTS)
    set(_moos_labels [=[geometry;formats]=])
    if(_moos_test MATCHES [=[\.XYSegListTest\.]=])
      list(APPEND _moos_labels [=[XYSegList]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsSeglTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsSegl]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
