if(DEFINED test_geometry_xyformatutils_seglr_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_seglr_TESTS)
    set(_moos_labels [=[geometry;formats;math;ray]=])
    if(_moos_test MATCHES [=[\.XYSeglrTest\.]=])
      list(APPEND _moos_labels [=[XYSeglr]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsSeglrTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsSeglr]=])
    endif()
    if(_moos_test MATCHES [=[\.SeglrTest\.]=])
      list(APPEND _moos_labels [=[Seglr]=])
    endif()
    if(_moos_test MATCHES [=[\.XYSeglrGeomUtilsTest\.]=])
      list(APPEND _moos_labels [=[XYSeglr]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
