if(DEFINED test_geometry_viewplug_settings_TESTS)
  foreach(_moos_test IN LISTS test_geometry_viewplug_settings_TESTS)
    set(_moos_labels [=[geometry;ViewPlugSettings;viewer_plugins]=])
    if(_moos_test MATCHES [=[\.HintHolderTest\.]=])
      list(APPEND _moos_labels [=[HintHolder]=])
    endif()
    if(_moos_test MATCHES [=[\.VPlugGeoSettingsTest\.]=])
      list(APPEND _moos_labels [=[VPlug_GeoSettings]=])
    endif()
    if(_moos_test MATCHES [=[\.VPlugVehiSettingsTest\.]=])
      list(APPEND _moos_labels [=[VPlug_VehiSettings]=])
    endif()
    if(_moos_test MATCHES [=[\.VPlugDropPointsTest\.]=])
      list(APPEND _moos_labels [=[VPlug_DropPoints]=])
    endif()
    if(_moos_test MATCHES [=[\.VPlugGeoShapesMapTest\.]=])
      list(APPEND _moos_labels [=[VPlug_GeoShapesMap]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
