if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/behaviors_colregs/Core/test_behaviors_colregs_velocity_filter[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/behaviors_colregs/Core/test_behaviors_colregs_velocity_filter[1]_tests.cmake")
else()
  add_test(test_behaviors_colregs_velocity_filter_NOT_BUILT test_behaviors_colregs_velocity_filter_NOT_BUILT)
endif()
