if(DEFINED test_geometry_xyformatutils_poly_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_poly_TESTS)
    set(_moos_labels [=[geometry;formats]=])
    if(_moos_test MATCHES [=[\.XYPolygonTest\.]=])
      list(APPEND _moos_labels [=[XYPolygon]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsPolyTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsPoly]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
