if(DEFINED test_geometry_pathutils_TESTS)
  foreach(_moos_test IN LISTS test_geometry_pathutils_TESTS)
    set(_moos_labels [=[geometry;math;waypoint]=])
    if(_moos_test MATCHES [=[\.PathUtilsGreedyPathTest\.]=])
      list(APPEND _moos_labels [=[PathUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.EdgeTagTest\.]=])
      list(APPEND _moos_labels [=[EdgeTag]=])
    endif()
    if(_moos_test MATCHES [=[\.EdgeTagSetTest\.]=])
      list(APPEND _moos_labels [=[EdgeTagSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
