if(DEFINED test_mbutil_bundleout_TESTS)
  foreach(_moos_test IN LISTS test_mbutil_bundleout_TESTS)
    set(_moos_labels [=[mbutil]=])
    if(_moos_test MATCHES [=[\.BundleOutTest\.]=])
      list(APPEND _moos_labels [=[BundleOut]=])
    endif()
    if(_moos_test MATCHES [=[\.OpenURLTest\.]=])
      list(APPEND _moos_labels [=[OpenURL]=])
    endif()
    if(_moos_test MATCHES [=[\.ReleaseInfoTest\.]=])
      list(APPEND _moos_labels [=[ReleaseInfo]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
