if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/tagrep/TagHandler/test_tagrep_tag_handler[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/tagrep/TagHandler/test_tagrep_tag_handler[1]_tests.cmake")
else()
  add_test(test_tagrep_tag_handler_NOT_BUILT test_tagrep_tag_handler_NOT_BUILT)
endif()
