if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/aloghelm/HelmReporter/test_aloghelm_helm_reporter[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/aloghelm/HelmReporter/test_aloghelm_helm_reporter[1]_tests.cmake")
else()
  add_test(test_aloghelm_helm_reporter_NOT_BUILT test_aloghelm_helm_reporter_NOT_BUILT)
endif()
