if(DEFINED test_bhvutil_legrun_TESTS)
  foreach(_moos_test IN LISTS test_bhvutil_legrun_TESTS)
    set(_moos_labels [=[bhvutil;BHV_LegRun]=])
    if(_moos_test MATCHES [=[\.LegRunTest\.]=])
      list(APPEND _moos_labels [=[LegRun]=])
    endif()
    if(_moos_test MATCHES [=[\.LegRunSetTest\.]=])
      list(APPEND _moos_labels [=[LegRunSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
