if(DEFINED test_logutils_file_processing_TESTS)
  foreach(_moos_test IN LISTS test_logutils_file_processing_TESTS)
    set(_moos_labels [=[logutils;ALogFiles]=])
    if(_moos_test MATCHES [=[\.ScanReportTest\.]=])
      list(APPEND _moos_labels [=[ScanReport]=])
    endif()
    if(_moos_test MATCHES [=[\.ALogScannerTest\.]=])
      list(APPEND _moos_labels [=[ALogScanner]=])
    endif()
    if(_moos_test MATCHES [=[\.ALogSorterTest\.]=])
      list(APPEND _moos_labels [=[ALogSorter]=])
    endif()
    if(_moos_test MATCHES [=[\.SplitHandlerTest\.]=])
      list(APPEND _moos_labels [=[SplitHandler]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
