if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/uflddelve/TransRecord/test_uflddelve_trans_record[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/uflddelve/TransRecord/test_uflddelve_trans_record[1]_tests.cmake")
else()
  add_test(test_uflddelve_trans_record_NOT_BUILT test_uflddelve_trans_record_NOT_BUILT)
endif()
