if(DEFINED test_uflddelve_trans_record_TESTS)
  foreach(_moos_test IN LISTS test_uflddelve_trans_record_TESTS)
    set(_moos_labels [=[uflddelve;TransRecord]=])
    if(_moos_test MATCHES [=[\.TransRecordTest\.]=])
      list(APPEND _moos_labels [=[TransRecord]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
