if(DEFINED test_geometry_xyformatutils_marker_TESTS)
  foreach(_moos_test IN LISTS test_geometry_xyformatutils_marker_TESTS)
    set(_moos_labels [=[geometry;formats]=])
    if(_moos_test MATCHES [=[\.XYMarkerTest\.]=])
      list(APPEND _moos_labels [=[XYMarker]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsMarkerTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsMarker]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
