if(DEFINED test_contacts_noderider_TESTS)
  foreach(_moos_test IN LISTS test_contacts_noderider_TESTS)
    set(_moos_labels [=[contacts;NodeReport]=])
    if(_moos_test MATCHES [=[\.NodeRiderTest\.]=])
      list(APPEND _moos_labels [=[NodeRider]=])
    endif()
    if(_moos_test MATCHES [=[\.NodeRiderSetTest\.]=])
      list(APPEND _moos_labels [=[NodeRiderSet]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
