
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/bin/"
      - "/usr/local/bin/"
      - "/usr/texbin/"
      - "/Library/TeX/texbin/"
      - "/Users/charlesbenjamin/texbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/bin/"
      - "/Users/charlesbenjamin/flutter/bin/"
      - "/Applications/"
      - "/usr/X11/bin/"
      - "/Users/charlesbenjamin/bin/"
      - "/sbin/"
      - "/usr/sbin/"
      - "/Users/charlesbenjamin/project-pavlab/utils/bin/"
      - "/Applications/Emacs.app/Contents/MacOS/"
      - "/Applications/VMware Fusion.app/Contents/Library/"
      - "/Applications/Docker.app/Contents/Resources/bin/"
      - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/"
      - "/Users/charlesbenjamin/Library/Python/3.8/bin/"
      - "/Users/charlesbenjamin/opt/anaconda3/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/charlesbenjamin/moos-ivp-2680/bin/"
      - "/Users/charlesbenjamin/moos-ivp/scripts/"
      - "/Users/charlesbenjamin/moos-ivp/bin/"
      - "/Users/charlesbenjamin/moos-ivp-5i/bin/"
      - "/Users/charlesbenjamin/moos-ivp-swarm/bin/"
      - "/Users/charlesbenjamin/moos-ivp-swarm/scripts/"
      - "/my/full/directory/"
      - "/Users/charlesbenjamin/moos-ivp-uav-base/bin/"
      - "/Users/charlesbenjamin/moos-ivp-uav-base/scripts/"
      - "/Users/charlesbenjamin/moos-ivp-pavlab/bin/"
      - "/Users/charlesbenjamin/moos-ivp-pavlab/scripts/"
      - "/Users/charlesbenjamin/.local/bin/"
      - "/Users/charlesbenjamin/moos-ivp-pearl/scripts/"
      - "/Users/charlesbenjamin/moos-ivp-pearl/bin/"
      - "/Users/charlesbenjamin/pablo-common/bin/"
      - "/snap/bin/"
      - "/Users/charlesbenjamin/moos-ivp/"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/bin"
        - "/usr/local/bin"
        - "/usr/texbin"
        - "/Library/TeX/texbin"
        - "/Users/charlesbenjamin/texbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/bin"
        - "/Users/charlesbenjamin/flutter/bin"
        - "/Applications"
        - "/usr/X11/bin"
        - "/Users/charlesbenjamin/bin"
        - "/sbin"
        - "/usr/sbin"
        - "/Users/charlesbenjamin/project-pavlab/utils/bin"
        - "/Applications/Emacs.app/Contents/MacOS/"
        - "/Applications/VMware Fusion.app/Contents/Library"
        - "/Applications/VMware Fusion.app/Contents/Library"
        - "/Applications/Docker.app/Contents/Resources/bin"
        - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
        - "/Users/charlesbenjamin/Library/Python/3.8/bin"
        - "/Users/charlesbenjamin/opt/anaconda3/bin"
        - "/opt/homebrew/bin"
        - "/Users/charlesbenjamin/moos-ivp-2680/bin"
        - "/Users/charlesbenjamin/moos-ivp/scripts"
        - "/Users/charlesbenjamin/moos-ivp/bin"
        - "/Users/charlesbenjamin/moos-ivp-5i/bin"
        - "/Users/charlesbenjamin/moos-ivp-swarm/bin"
        - "/Users/charlesbenjamin/moos-ivp-swarm/scripts"
        - "/my/full/directory/"
        - "/Users/charlesbenjamin/moos-ivp-uav-base/bin"
        - "/Users/charlesbenjamin/moos-ivp-uav-base/scripts"
        - "/Users/charlesbenjamin/moos-ivp-pavlab/bin"
        - "/Users/charlesbenjamin/moos-ivp-pavlab/scripts"
        - "/Users/charlesbenjamin/.local/bin"
        - "/Users/charlesbenjamin/moos-ivp-pearl/scripts"
        - "/Users/charlesbenjamin/moos-ivp-pearl/bin"
        - "/Users/charlesbenjamin/moos-ivp/bin"
        - "/Users/charlesbenjamin/moos-ivp/scripts"
        - "/Users/charlesbenjamin/pablo-common/bin"
        - "/bin"
        - "/snap/bin"
        - "/usr/bin"
        - "/usr/local/bin"
        - "/opt/homebrew/bin"
        - "/opt/local/bin"
        - "/usr/X11/bin"
        - "/sbin"
        - "/usr/sbin"
        - "/Users/charlesbenjamin/moos-ivp"
        - "/Users/charlesbenjamin/moos-ivp/bin"
        - "/Users/charlesbenjamin/moos-ivp/scripts"
        - "/Users/charlesbenjamin/moos-ivp-uav-base/bin"
        - "/Users/charlesbenjamin/moos-ivp-swarm/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.3.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/usr/bin/"
      - "/usr/local/bin/"
      - "/usr/texbin/"
      - "/Library/TeX/texbin/"
      - "/Users/charlesbenjamin/texbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/bin/"
      - "/Users/charlesbenjamin/flutter/bin/"
      - "/Applications/"
      - "/usr/X11/bin/"
      - "/Users/charlesbenjamin/bin/"
      - "/sbin/"
      - "/usr/sbin/"
      - "/Users/charlesbenjamin/project-pavlab/utils/bin/"
      - "/Applications/Emacs.app/Contents/MacOS/"
      - "/Applications/VMware Fusion.app/Contents/Library/"
      - "/Applications/Docker.app/Contents/Resources/bin/"
      - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/"
      - "/Users/charlesbenjamin/Library/Python/3.8/bin/"
      - "/Users/charlesbenjamin/opt/anaconda3/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/charlesbenjamin/moos-ivp-2680/bin/"
      - "/Users/charlesbenjamin/moos-ivp/scripts/"
      - "/Users/charlesbenjamin/moos-ivp/bin/"
      - "/Users/charlesbenjamin/moos-ivp-5i/bin/"
      - "/Users/charlesbenjamin/moos-ivp-swarm/bin/"
      - "/Users/charlesbenjamin/moos-ivp-swarm/scripts/"
      - "/my/full/directory/"
      - "/Users/charlesbenjamin/moos-ivp-uav-base/bin/"
      - "/Users/charlesbenjamin/moos-ivp-uav-base/scripts/"
      - "/Users/charlesbenjamin/moos-ivp-pavlab/bin/"
      - "/Users/charlesbenjamin/moos-ivp-pavlab/scripts/"
      - "/Users/charlesbenjamin/.local/bin/"
      - "/Users/charlesbenjamin/moos-ivp-pearl/scripts/"
      - "/Users/charlesbenjamin/moos-ivp-pearl/bin/"
      - "/Users/charlesbenjamin/pablo-common/bin/"
      - "/snap/bin/"
      - "/Users/charlesbenjamin/moos-ivp/"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/usr/bin"
        - "/usr/local/bin"
        - "/usr/texbin"
        - "/Library/TeX/texbin"
        - "/Users/charlesbenjamin/texbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/bin"
        - "/Users/charlesbenjamin/flutter/bin"
        - "/Applications"
        - "/usr/X11/bin"
        - "/Users/charlesbenjamin/bin"
        - "/sbin"
        - "/usr/sbin"
        - "/Users/charlesbenjamin/project-pavlab/utils/bin"
        - "/Applications/Emacs.app/Contents/MacOS/"
        - "/Applications/VMware Fusion.app/Contents/Library"
        - "/Applications/VMware Fusion.app/Contents/Library"
        - "/Applications/Docker.app/Contents/Resources/bin"
        - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
        - "/Users/charlesbenjamin/Library/Python/3.8/bin"
        - "/Users/charlesbenjamin/opt/anaconda3/bin"
        - "/opt/homebrew/bin"
        - "/Users/charlesbenjamin/moos-ivp-2680/bin"
        - "/Users/charlesbenjamin/moos-ivp/scripts"
        - "/Users/charlesbenjamin/moos-ivp/bin"
        - "/Users/charlesbenjamin/moos-ivp-5i/bin"
        - "/Users/charlesbenjamin/moos-ivp-swarm/bin"
        - "/Users/charlesbenjamin/moos-ivp-swarm/scripts"
        - "/my/full/directory/"
        - "/Users/charlesbenjamin/moos-ivp-uav-base/bin"
        - "/Users/charlesbenjamin/moos-ivp-uav-base/scripts"
        - "/Users/charlesbenjamin/moos-ivp-pavlab/bin"
        - "/Users/charlesbenjamin/moos-ivp-pavlab/scripts"
        - "/Users/charlesbenjamin/.local/bin"
        - "/Users/charlesbenjamin/moos-ivp-pearl/scripts"
        - "/Users/charlesbenjamin/moos-ivp-pearl/bin"
        - "/Users/charlesbenjamin/moos-ivp/bin"
        - "/Users/charlesbenjamin/moos-ivp/scripts"
        - "/Users/charlesbenjamin/pablo-common/bin"
        - "/bin"
        - "/snap/bin"
        - "/usr/bin"
        - "/usr/local/bin"
        - "/opt/homebrew/bin"
        - "/opt/local/bin"
        - "/usr/X11/bin"
        - "/sbin"
        - "/usr/sbin"
        - "/Users/charlesbenjamin/moos-ivp"
        - "/Users/charlesbenjamin/moos-ivp/bin"
        - "/Users/charlesbenjamin/moos-ivp/scripts"
        - "/Users/charlesbenjamin/moos-ivp-uav-base/bin"
        - "/Users/charlesbenjamin/moos-ivp-swarm/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
