if(DEFINED test_genutil_string_file_TESTS)
  foreach(_moos_test IN LISTS test_genutil_string_file_TESTS)
    set(_moos_labels [=[genutil]=])
    if(_moos_test MATCHES [=[\.StringUtilTest\.]=])
      list(APPEND _moos_labels [=[stringutil]=])
    endif()
    if(_moos_test MATCHES [=[\.FileUtilTest\.]=])
      list(APPEND _moos_labels [=[fileutil]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
