if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/genutil/StringAndFile/test_genutil_string_file[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/genutil/StringAndFile/test_genutil_string_file[1]_tests.cmake")
else()
  add_test(test_genutil_string_file_NOT_BUILT test_genutil_string_file_NOT_BUILT)
endif()
