if(DEFINED test_mbutil_misc_objects_TESTS)
  foreach(_moos_test IN LISTS test_mbutil_misc_objects_TESTS)
    set(_moos_labels [=[mbutil]=])
    if(_moos_test MATCHES [=[\.AckMessageTest\.]=])
      list(APPEND _moos_labels [=[AckMessage]=])
    endif()
    if(_moos_test MATCHES [=[\.MailFlagSetTest\.]=])
      list(APPEND _moos_labels [=[MailFlagSet]=])
    endif()
    if(_moos_test MATCHES [=[\.TStampTest\.]=])
      list(APPEND _moos_labels [=[TStamp]=])
    endif()
    if(_moos_test MATCHES [=[\.OdometerTest\.]=])
      list(APPEND _moos_labels [=[Odometer]=])
    endif()
    if(_moos_test MATCHES [=[\.FileBufferTest\.]=])
      list(APPEND _moos_labels [=[FileBuffer]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
