if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/mbutil/MiscObjects/test_mbutil_misc_objects[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/mbutil/MiscObjects/test_mbutil_misc_objects[1]_tests.cmake")
else()
  add_test(test_mbutil_misc_objects_NOT_BUILT test_mbutil_misc_objects_NOT_BUILT)
endif()
