if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ivpcore/CoreObjects/test_ivpcore_core_objects[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ivpcore/CoreObjects/test_ivpcore_core_objects[1]_tests.cmake")
else()
  add_test(test_ivpcore_core_objects_NOT_BUILT test_ivpcore_core_objects_NOT_BUILT)
endif()
