if(DEFINED test_ivpcore_core_objects_TESTS)
  foreach(_moos_test IN LISTS test_ivpcore_core_objects_TESTS)
    set(_moos_labels [=[ivpcore;pHelmIvP;math]=])
    if(_moos_test MATCHES [=[\.IvPDomainTest\.]=])
      list(APPEND _moos_labels [=[IvPDomain]=])
    endif()
    if(_moos_test MATCHES [=[\.IvPBoxTest\.]=])
      list(APPEND _moos_labels [=[IvPBox]=])
    endif()
    if(_moos_test MATCHES [=[\.BoxSetTest\.]=])
      list(APPEND _moos_labels [=[BoxSet]=])
    endif()
    if(_moos_test MATCHES [=[\.IvPGridTest\.]=])
      list(APPEND _moos_labels [=[IvPGrid]=])
    endif()
    if(_moos_test MATCHES [=[\.CompactorNullTest\.]=])
      list(APPEND _moos_labels [=[CompactorNull]=])
    endif()
    if(_moos_test MATCHES [=[\.PDMapTest\.]=])
      list(APPEND _moos_labels [=[PDMap]=])
    endif()
    if(_moos_test MATCHES [=[\.IvPFunctionTest\.]=])
      list(APPEND _moos_labels [=[IvPFunction]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
