if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/MiscGeometryTools/test_geometry_misc_geometry_tools[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/geometry/MiscGeometryTools/test_geometry_misc_geometry_tools[1]_tests.cmake")
else()
  add_test(test_geometry_misc_geometry_tools_NOT_BUILT test_geometry_misc_geometry_tools_NOT_BUILT)
endif()
