if(DEFINED test_geometry_misc_geometry_tools_TESTS)
  foreach(_moos_test IN LISTS test_geometry_misc_geometry_tools_TESTS)
    set(_moos_labels [=[geometry;MiscGeometryTools]=])
    if(_moos_test MATCHES [=[\.SeglrUtilsTest\.]=])
      list(APPEND _moos_labels [=[SeglrUtils]=])
    endif()
    if(_moos_test MATCHES [=[\.WallEngineTest\.]=])
      list(APPEND _moos_labels [=[WallEngine]=])
    endif()
    if(_moos_test MATCHES [=[\.XYEncodersTest\.]=])
      list(APPEND _moos_labels [=[XYEncoders]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFormatUtilsConvexGridTest\.]=])
      list(APPEND _moos_labels [=[XYFormatUtilsConvexGrid]=])
    endif()
    if(_moos_test MATCHES [=[\.XYArtifactGridTest\.]=])
      list(APPEND _moos_labels [=[XYArtifactGrid]=])
    endif()
    if(_moos_test MATCHES [=[\.XYFieldGeneratorTest\.]=])
      list(APPEND _moos_labels [=[XYFieldGenerator]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
