if(DEFINED test_ipfview_core_TESTS)
  foreach(_moos_test IN LISTS test_ipfview_core_TESTS)
    set(_moos_labels [=[ipfview]=])
    if(_moos_test MATCHES [=[\.IPFEntryTest\.]=])
      list(APPEND _moos_labels [=[IPF_Entry]=])
    endif()
    if(_moos_test MATCHES [=[\.IPFBundleTest\.]=])
      list(APPEND _moos_labels [=[IPF_Bundle]=])
    endif()
    if(_moos_test MATCHES [=[\.IPFBundleSeriesTest\.]=])
      list(APPEND _moos_labels [=[IPF_BundleSeries]=])
    endif()
    if(_moos_test MATCHES [=[\.IPFViewUtilsTest\.]=])
      list(APPEND _moos_labels [=[IPF_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.IPFUtilsTest\.]=])
      list(APPEND _moos_labels [=[IPF_Utils]=])
    endif()
    if(_moos_test MATCHES [=[\.QuadSetTest\.]=])
      list(APPEND _moos_labels [=[QuadSet]=])
    endif()
    if(_moos_test MATCHES [=[\.Quad3DTest\.]=])
      list(APPEND _moos_labels [=[Quad3D]=])
    endif()
    if(_moos_test MATCHES [=[\.QuadSet1DTest\.]=])
      list(APPEND _moos_labels [=[QuadSet1D]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
