if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ipfview/Core/test_ipfview_core[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ipfview/Core/test_ipfview_core[1]_tests.cmake")
else()
  add_test(test_ipfview_core_NOT_BUILT test_ipfview_core_NOT_BUILT)
endif()
