if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogrm/FiltHandler/test_alogrm_filt_handler[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogrm/FiltHandler/test_alogrm_filt_handler[1]_tests.cmake")
else()
  add_test(test_alogrm_filt_handler_NOT_BUILT test_alogrm_filt_handler_NOT_BUILT)
endif()
