if(DEFINED test_ufldcollisiondetect_cpa_monitor_TESTS)
  foreach(_moos_test IN LISTS test_ufldcollisiondetect_cpa_monitor_TESTS)
    set(_moos_labels [=[ufldcollisiondetect;uFldCollisionDetect;CollisionDetect]=])
    if(_moos_test MATCHES [=[\.CPAMonitorTest\.]=])
      list(APPEND _moos_labels [=[CPAMonitor]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
