if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ufldcollisiondetect/CPAMonitor/test_ufldcollisiondetect_cpa_monitor[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/ufldcollisiondetect/CPAMonitor/test_ufldcollisiondetect_cpa_monitor[1]_tests.cmake")
else()
  add_test(test_ufldcollisiondetect_cpa_monitor_NOT_BUILT test_ufldcollisiondetect_cpa_monitor_NOT_BUILT)
endif()
