if(DEFINED test_ivpbuild_aof_TESTS)
  foreach(_moos_test IN LISTS test_ivpbuild_aof_TESTS)
    set(_moos_labels [=[ivpbuild;math;AOF]=])
    if(_moos_test MATCHES [=[\.AOFLinearTest\.]=])
      list(APPEND _moos_labels [=[AOF_Linear]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFQuadraticTest\.]=])
      list(APPEND _moos_labels [=[AOF_Quadratic]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFGaussianTest\.]=])
      list(APPEND _moos_labels [=[AOF_Gaussian]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFMultiGaussianTest\.]=])
      list(APPEND _moos_labels [=[AOF_MGaussian]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFRingTest\.]=])
      list(APPEND _moos_labels [=[AOF_Ring]=])
    endif()
    if(_moos_test MATCHES [=[\.AOFRingsTest\.]=])
      list(APPEND _moos_labels [=[AOF_Rings]=])
    endif()
    set_tests_properties(${_moos_test} PROPERTIES LABELS "${_moos_labels}")
  endforeach()
endif()
