if(EXISTS "/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogclip/ALogClip/test_alogclip_alogclip[1]_tests.cmake")
  include("/Users/charlesbenjamin/moos-ivp-cicd-testing/build-coverage/tests/cpp/alogclip/ALogClip/test_alogclip_alogclip[1]_tests.cmake")
else()
  add_test(test_alogclip_alogclip_NOT_BUILT test_alogclip_alogclip_NOT_BUILT)
endif()
